[build]
  functions = "contact-form-backend/netlify-functions"
  publish = "pacific-nursing-solution/dist"
  environment = { NODE_VERSION = "21" }

[[redirects]]
  from = "/send-email"
  to = "/.netlify/functions/send-email"
  status = 200
  force = true

[[redirects]]
  from = "/apply-now"
  to = "/.netlify/functions/apply-now"
  status = 200
  force = true

[[redirects]]
  from = "/subscribe"
  to = "/.netlify/functions/subscribe"
  status = 200
  force = true

[dev]
  targetPort = 5174
  functions = "contact-form-backend/netlify-functions"

[functions]
  directory = "contact-form-backend/netlify-functions"

