[build]
  publish = "public" # This should be the directory you are deploying
  command = "npm run build" # Make sure this command builds your site

[functions]
  directory = "netlify/functions" # Path to your functions directory
