[build]
  command = "cd pacific-nursing-solution && npm run build"
  functions = "contact-form-backend/netlify-functions"
  publish = "pacific-nursing-solution/dist"

[context.production.environment]
  NODE_VERSION = "16.18.0"

[build.environment]
  NODE_OPTIONS = "--max-old-space-size=4096"

[[redirects]]
  from = "/send-email"
  to = "/.netlify/functions/send-email"
  status = 200
  force = true

[[redirects]]
  from = "/apply-now"
  to = "/.netlify/functions/apply-now"
  status = 200
  force = true

[[redirects]]
  from = "/subscribe"
  to = "/.netlify/functions/subscribe"
  status = 200
  force = true

# Add a fallback redirect for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  targetPort = 5174
  functions = "contact-form-backend/netlify-functions"

[functions]
  directory = "contact-form-backend/netlify-functions"
